#!/bin/bash
if [ "$#" -ne 3 ]; then
    echo "Not enough information provided..."
    exit 1
fi

which_node=$(curl --silent http://www.mcs.anl.gov/research/projects/waggle/downloads/beehive1/node-info.txt | grep -i $1' ' | tr "|" " "| tr -s " " | cut -d " " -f 4 | sed "s/0000001E061/001E061/g" |  tr '[:upper:]' '[:lower:]')
how_long_ago=$2
how_long=$3

if [ "$(echo $which_node | tr " " "\n" | wc -l )" -eq "1" ]; then
if [ ! -z "$which_node" ];then
rm 2017*.csv
rm sensor_data_set.csv
rm 2017*.csv.*
for i in `seq 0 $how_long`;
do
    wget_output=$(wget "http://www.mcs.anl.gov/research/projects/waggle/downloads/datasets/2/"$which_node/"$(date  --date="$(($i + $how_long_ago)) days ago" +%Y-%m-%d).csv.gz")
    if [ $? == 0 ]; then
        gunzip "$(date  --date="$(($i + $how_long_ago)) days ago" +%Y-%m-%d).csv.gz" 
    fi
done     
cat $(ls 2017*.csv | sort -V)  |  tr " " "_" | tr "\/" "_" > sensor_data_set.csv
rm -rf 2017*.csv
echo "Downloaded files and created source dataset..."
else
echo "Unable to find node "$1
fi
else 
echo "!!! Several ports found, please be more specific with node details ..."$which_port
fi

