#!/bin/bash
if [ "$#" -ne 3 ]; then
    echo "Not enough information provided..."
    exit 1
fi
./getdatasets $1 $2 $3
python3 beehive_csv.py
mv sensor_data_set_converted.csv sensor_data_set.csv
./plot sensor_data_set.csv
