#!/bin/bash
# ANL:waggle-license
# This file is part of the Waggle Platform.  Please see the file
# LICENSE.waggle.txt for the legal details of the copyright and software
# license.  For more details on the Waggle project, visit:
#          http://www.wa8.gl
# ANL:waggle-license

if [ "$#" -ne 3 ]; then
    echo "Not enough information provided..."
    exit 1
fi

which_node=$(curl --silent http://www.mcs.anl.gov/research/projects/waggle/downloads/beehive1/node-info.txt | grep -i $1' ' | tr "|" " "| tr -s " " | cut -d " " -f 4 | sed "s/0000001E061/001E061/g" | sed "s/0000020000000/020000000/g" |  tr '[:upper:]' '[:lower:]')
how_long_ago=$2
how_long=$3

if [ "$(echo $which_node | tr " " "\n" | wc -l )" -eq "1" ]; then
if [ ! -z "$which_node" ];then
rm 201*.csv
rm sensor_data_set.csv
rm 201*.csv.*
for i in `seq 0 $how_long`;
do
    if [ "$(uname)" = Linux ]; then
        wget_output=$(wget  "http://www.mcs.anl.gov/research/projects/waggle/downloads/datasets/2/"$which_node/"$(date  --date="$(($i + $how_long_ago)) days ago" +%Y-%m-%d).csv.gz")
    else
        wget_output=$(wget  "http://www.mcs.anl.gov/research/projects/waggle/downloads/datasets/2/"$which_node/"$(date -v-$(($i + $how_long_ago))d +%Y-%m-%d)".csv.gz)
    fi
    if [ $? == 0 ]; then
    if [ "$(uname)" = Linux ]; then
        gunzip "$(date  --date="$(($i + $how_long_ago)) days ago" +%Y-%m-%d).csv.gz" 
    else
        gunzip "$(date -v-$(($i + $how_long_ago))d +%Y-%m-%d).csv.gz" 
    fi
      
    fi
done     

if [ "$(uname)" = Linux ]; then
    cat $(ls 201*.csv | sort -V)  |  tr " " "_" | tr "\/" "_" > sensor_data_set.csv
    rm -rf 201*.csv

else
    cat $(ls 201*.csv | sort)  |  tr " " "_" | tr "\/" "_" > sensor_data_set.csv
    rm -rf 201*.csv
fi

echo "Downloaded files and created source dataset..."
else
echo "Unable to find node "$1
fi
else 
echo "!!! Several ports found, please be more specific with node details ..."$which_port
fi

