#!/bin/bash
### wget, dtrx command neccessary
if [ "$#" -ne 3 ]; then
    echo "Not enough information provided..."
    exit 1
fi

which_node=$(curl --silent http://beehive1.mcs.anl.gov/node-info.txt | grep -i $1' ' | tr "|" " "| tr -s " " | cut -d " " -f 4 | sed "s/0000001E061/001E061/g" |  tr '[:upper:]' '[:lower:]')
how_long_ago=$2
how_long=$3

if [ "$(echo $which_node | tr " " "\n" | wc -l )" -eq "1" ]; then
if [ ! -z "$which_node" ];then
rm 201*.csv
rm sensor_data_set.csv
rm 201*.csv.*

if [[ "$(uname)" == "Darwin" ]]; then
    for i in `seq 0 $how_long`;
    do
        echo "The operation system is Mac"
        wget_output=$(wget "http://beehive1.mcs.anl.gov/datasets/2/"$which_node/"$(date  -v -"$(($i + $how_long_ago))"d +%Y-%m-%d).csv.gz")
        if [ $? == 0 ]; then
            dtrx "$(date  -v -"$(($i + $how_long_ago))"d +%Y-%m-%d).csv.gz"
            rm "$(date  -v -"$(($i + $how_long_ago))"d +%Y-%m-%d).csv.gz"
        fi
    done
    echo "done downloading data"
    cat $(ls 201*.csv | sort -f)  |  tr " " "_" | tr "\/" "_" > sensor_data_set.csv
    echo "done changing file name"
elif [[ "$(uname)" == "Linux" ]]; then
    for i in `seq 0 $how_long`;
    do
        echo "The operation system is Linux"
        wget_output=$(wget "http://beehive1.mcs.anl.gov/datasets/2/"$which_node/"$(date  --date="$(($i + $how_long_ago)) days ago" +%Y-%m-%d).csv.gz")
        if [ $? == 0 ]; then
            dtrx "$(date  --date="$(($i + $how_long_ago)) days ago" +%Y-%m-%d).csv.gz"
            rm "$(date  --date="$(($i + $how_long_ago)) days ago" +%Y-%m-%d).csv.gz"
        fi
    done
    cat $(ls 201*.csv | sort -V)  |  tr " " "_" | tr "\/" "_" > sensor_data_set.csv
else
    echo "The operatoin system is not Linux nor Mac; un-noticed system"
fi

rm -rf 201*.csv
echo "Downloaded files and created source dataset..."
else
echo "Unable to find node "$1
fi
else
echo "!!! Several ports found, please be more specific with node details ..."$which_port
fi

node_descr=$(curl --silent http://beehive1.mcs.anl.gov/node-info.txt | grep -i $(head -1 "./sensor_data_set.csv" | cut -d ";" -f 1) | tr -s " " | cut -d '|' -f 5)
node_loc=$(curl --silent http://beehive1.mcs.anl.gov/node-info.txt | grep -i $(head -1 "./sensor_data_set.csv" | cut -d ";" -f 1) | tr -s " " | cut -d '|' -f 6)
echo $node_loc > node_loc
echo $node_descr > node_name
